name: Test-Coverage

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEKEY }}
      with:
        coverageCommand: yarn coverage
